---
openapi: 3.0.1
info:
  title: JSON:API
  version: v1
paths:
  "/api/people":
    get:
      summary: list people
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
