---
- :method: :upcoming_user_events
  :constant: Event::ListsController
  :wagon: swb
  :source_file: hitobito/app/controllers/event/lists_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/event/lists_controller.rb
  :patch_file_line: 32
- :method: :person_attributes
  :constant: Export::Tabular::People::PeopleAddress
  :wagon: swb
  :source_file: hitobito/app/domain/export/tabular/people/people_address.rb
  :patch_file: hitobito_swb/app/domain/swb/export/tabular/people/people_address.rb
  :patch_file_line: 9
- :method: :cancel_all_invoices
  :constant: InvoiceListsController
  :wagon: swb
  :source_file: hitobito/app/controllers/invoice_lists_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/invoice_lists_controller.rb
  :patch_file_line: 11
- :method: :index
  :constant: JsonApi::EventsController
  :wagon: swb
  :source_file: hitobito/app/controllers/json_api/events_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/json_api/events_controller.rb
  :patch_file_line: 13
- :method: :filter_entries
  :constant: PeopleController
  :wagon: swb
  :source_file: hitobito/app/controllers/people_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/people_controller.rb
  :patch_file_line: 21
- :method: :full_label
  :constant: PersonDecorator
  :wagon: swb
  :source_file: hitobito/app/decorators/person_decorator.rb
  :patch_file: hitobito_swb/app/decorators/swb/person_decorator.rb
  :patch_file_line: 11
- :method: :to_s
  :constant: Role
  :wagon: swb
  :source_file: hitobito/app/models/role.rb
  :patch_file: hitobito_swb/app/models/swb/role.rb
  :patch_file_line: 27
- :method: :create_new_role_and_destroy_old_role
  :constant: RolesController
  :wagon: swb
  :source_file: hitobito/app/controllers/roles_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/roles_controller.rb
  :patch_file_line: 22
- :method: :render_entries_pdf
  :constant: Event::ParticipationsController
  :wagon: sww
  :source_file: hitobito/app/controllers/event/participations_controller.rb
  :patch_file: hitobito_sww/app/controllers/sww/event/participations_controller.rb
  :patch_file_line: 11
- :method: :articles
  :constant: Export::Pdf::Invoice::Articles
  :wagon: sww
  :source_file: hitobito/app/domain/export/pdf/invoice/articles.rb
  :patch_file: hitobito_sww/app/domain/sww/export/pdf/invoice/articles.rb
  :patch_file_line: 69
- :method: :render
  :constant: Export::Pdf::Invoice::Articles
  :wagon: sww
  :source_file: hitobito/app/domain/export/pdf/invoice/articles.rb
  :patch_file: hitobito_sww/app/domain/sww/export/pdf/invoice/articles.rb
  :patch_file_line: 9
- :method: :total_data
  :constant: Export::Pdf::Invoice::Articles
  :wagon: sww
  :source_file: hitobito/app/domain/export/pdf/invoice/articles.rb
  :patch_file: hitobito_sww/app/domain/sww/export/pdf/invoice/articles.rb
  :patch_file_line: 49
- :method: :information
  :constant: Export::Pdf::Invoice::InvoiceInformation
  :wagon: sww
  :source_file: hitobito/app/domain/export/pdf/invoice/invoice_information.rb
  :patch_file: hitobito_sww/app/domain/sww/export/pdf/invoice/invoice_information.rb
  :patch_file_line: 19
- :method: :render
  :constant: Export::Pdf::Invoice::InvoiceInformation
  :wagon: sww
  :source_file: hitobito/app/domain/export/pdf/invoice/invoice_information.rb
  :patch_file: hitobito_sww/app/domain/sww/export/pdf/invoice/invoice_information.rb
  :patch_file_line: 9
- :method: :render_address
  :constant: Export::Pdf::Messages::Letter::Header
  :wagon: sww
  :source_file: hitobito/app/domain/export/pdf/messages/letter/header.rb
  :patch_file: hitobito_sww/app/domain/sww/export/pdf/messages/letter/header.rb
  :patch_file_line: 9
- :method: :person_attributes
  :constant: Export::Tabular::People::PeopleFull
  :wagon: sww
  :source_file: hitobito/app/domain/export/tabular/people/people_full.rb
  :patch_file: hitobito_sww/app/domain/sww/export/tabular/people/people_full.rb
  :patch_file_line: 11
- :method: :roles
  :constant: Export::Tabular::People::PersonRow
  :wagon: sww
  :source_file: hitobito/app/domain/export/tabular/people/person_row.rb
  :patch_file: hitobito_sww/app/domain/sww/export/tabular/people/person_row.rb
  :patch_file_line: 11
- :method: :render_tabular
  :constant: Invoices::EvaluationsController
  :wagon: sww
  :source_file: hitobito/app/controllers/invoices/evaluations_controller.rb
  :patch_file: hitobito_sww/app/controllers/sww/invoices/evaluations_controller.rb
  :patch_file_line: 11
- :method: :scope_attrs
  :constant: Oauth::ProfilesController
  :wagon: sww
  :source_file: hitobito/app/controllers/oauth/profiles_controller.rb
  :patch_file: hitobito_sww/app/controllers/sww/oauth/profiles_controller.rb
  :patch_file_line: 11
- :method: :author_service_token_label
  :constant: PaperTrail::VersionDecorator
  :wagon: sww
  :source_file: hitobito/app/decorators/paper_trail/version_decorator.rb
  :patch_file: hitobito_sww/app/decorators/sww/paper_trail/version_decorator.rb
  :patch_file_line: 10
