inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails
  - ./lib/rubocop/cops/wagons/patched_method.rb

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

inherit_from:
  - .rubocop/rspec.yml
  - .rubocop/strict.yml
  - .rubocop/puzzle.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - Rakefile
    - db/**/*
    - config/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - app/assets/config.rb
    - node_modules/**/*

Lint/UselessAssignment:
  AutoCorrect: false

Rails/ToSWithArgument:
  Enabled: false
