version: '3.4'
services:
  db:
    image: mysql:5.7
    command:
    - --sort_buffer_size=2M
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --max_allowed_packet=32505856 # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    ports:
    - "33066:3306"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
    - db:/var/lib/mysql

volumes:
  db:
