// Copyright (c) 2026, hitobito AG. This file is part of
// hitobito and licensed under the Affero General Public License version 3
// or later. See the COPYING file at the top-level directory or at
// https://github.com/hitobito/hitobito.

// Before bundling, (re)writes generated files with explicit import lists,
// replacing what require.context() used to do at runtime - esbuild has no
// equivalent - built from tmp/wagon_assets_manifest.json (rake
// assets:wagon_js_manifest, scoped to *active* wagons, i.e. Wagons.all).

const { execFileSync } = require("child_process");
const esbuild = require("esbuild");
const { sync: globSync } = require("glob");
const coffeescript = require("coffeescript");
const fs = require("fs");
const path = require("path");

const WAGON_MANIFEST_PATH = "tmp/wagon_assets_manifest.json";
const GENERATED_JS_DIR = "app/javascript/generated";
const OUTPUT_DIR = "app/assets/builds";

// `rake assets:render_js_entries assets:wagon_js_manifest` (which renders
// gem-provided ERB entries and lists the *active* wagons' JS-relevant
// files) are wired as Rake prerequisites of `javascript:build`, but this
// script also runs directly via `yarn build` (e.g. the Procfile's `js`
// process in normal dev mode) - a plain `yarn`/`node` invocation never goes
// through Rake at all, so those steps need to run here too, or switching
// WAGONS would silently keep bundling whichever wagon was last rendered.
execFileSync("bundle", ["exec", "rake", "assets:render_js_entries", "assets:wagon_js_manifest"], { stdio: "inherit" });

fs.mkdirSync(GENERATED_JS_DIR, { recursive: true });

// Lets `import { Controller } from "controllers"` (used by
// app/components/*_controller.js) resolve to app/javascript/controllers.
const controllersAliasPlugin = {
  name: "controllers-alias",
  setup(build) {
    build.onResolve({ filter: /^controllers$/ }, () => ({
      path: path.resolve("app/javascript/controllers/index.js"),
    }));
  },
};

const wagons = fs.existsSync(WAGON_MANIFEST_PATH)
  ? JSON.parse(fs.readFileSync(WAGON_MANIFEST_PATH, "utf8"))
  : [];

const GENERATED_HEADER = "// Generated by esbuild.config.js - do not edit, regenerated on every build.\n";

const coffeePlugin = {
  name: "coffeescript",
  setup(build) {
    build.onLoad({ filter: /\.coffee$/ }, (args) => {
      const contents = coffeescript.compile(fs.readFileSync(args.path, "utf8"), { bare: true });
      return { contents, loader: "js" };
    });
  },
};

// --- app/javascript/generated/wagon_scripts.js ---
// Replaces app/javascript/javascripts/wagons.js.erb (its image
// require.context is dropped - Propshaft serves wagon images directly).
const wagonScriptImports = wagons
  .filter((wagon) => wagon.wagonScript)
  .map((wagon) => `import ${JSON.stringify(wagon.wagonScript)};`)
  .join("\n");
fs.writeFileSync(
  path.join(GENERATED_JS_DIR, "wagon_scripts.js"),
  `${GENERATED_HEADER}${wagonScriptImports}\n`
);

// --- app/javascript/generated/core_modules.js ---
// Replaces core.js's requireAll(require.context('../javascripts/modules', ...)).
const coreModuleImports = globSync("app/javascript/javascripts/modules/**/*.{js,coffee}")
  .map((file) => `import ${JSON.stringify(path.resolve(file))};`)
  .join("\n");
fs.writeFileSync(
  path.join(GENERATED_JS_DIR, "core_modules.js"),
  `${GENERATED_HEADER}${coreModuleImports}\n`
);

// --- app/javascript/controllers/generated_index.js ---
// Replaces the four require.context() calls that used to live in
// controllers/index.js (core, component and wagon controllers -
// Wagons.all/wagon.paths.path resolves correctly in both the sibling-dev
// and vendor/wagons layouts, so there's no need to distinguish them here).
//
// Stimulus identifier convention: path relative to the controllers root,
// `_controller.js` stripped, underscores->dashes per segment, joined with
// "--" - e.g. events/question_template_nested_form_controller.js becomes
// "events--question-template-nested-form" (dropping the "events--" prefix
// would break any data-controller="events--..." in the DOM).
function controllerIdentifier(controllersRoot, filePath, wagonName) {
  const relative = path.relative(controllersRoot, filePath).replace(/_controller\.js$/, "");
  const base = relative.split(path.sep).map((segment) => segment.replace(/_/g, "-")).join("--");
  if (!wagonName) return base;
  return `${wagonName.replace(/^hitobito_/, "").replace(/_/g, "-")}--${base}`;
}

const controllerEntries = [
  ...globSync("app/javascript/controllers/**/*_controller.js").map((file) => ({
    file: path.resolve(file),
    identifier: controllerIdentifier(path.resolve("app/javascript/controllers"), path.resolve(file)),
  })),
  ...globSync("app/components/**/*_controller.js").map((file) => ({
    file: path.resolve(file),
    identifier: controllerIdentifier(path.resolve("app/components"), path.resolve(file)),
  })),
  ...wagons.flatMap((wagon) =>
    wagon.controllers.map((file) => ({
      file,
      identifier: controllerIdentifier(wagon.controllersRoot, file, wagon.name),
    }))
  ),
];

const controllerLines = controllerEntries.map(
  (entry, i) => [`import Controller${i} from ${JSON.stringify(entry.file)};`, entry.identifier, i]
);
fs.writeFileSync(
  path.join("app/javascript/controllers", "generated_index.js"),
  `${GENERATED_HEADER}${controllerLines.map(([importLine]) => importLine).join("\n")}

export function registerGeneratedControllers(application) {
${controllerLines.map(([, identifier, i]) => `  application.register(${JSON.stringify(identifier)}, Controller${i});`).join("\n")}
}
`
);

// --- Bundle ---
const coreEntries = ["application", "core", "pass_verify"].map((name) => `app/javascript/packs/${name}.js`);
const wagonEntries = wagons.flatMap((wagon) => wagon.packs);

// Prune stale JS outputs left over from a *different* wagon (e.g. a
// previous wagon's agenda.js, when the newly active one has no such pack)
// - only touches *.js/*.js.map, so this can't clobber the CSS build's own
// outputs (which are plain *.css, --no-source-map).
const expectedBasenames = new Set(
  [...coreEntries, ...wagonEntries].flatMap((entry) => {
    const base = path.basename(entry, ".js");
    return [`${base}.js`, `${base}.js.map`];
  })
);
for (const existing of [...globSync(`${OUTPUT_DIR}/*.js`), ...globSync(`${OUTPUT_DIR}/*.js.map`)]) {
  if (!expectedBasenames.has(path.basename(existing))) fs.unlinkSync(existing);
}

const buildOptions = {
  entryPoints: [...coreEntries, ...wagonEntries],
  bundle: true,
  outdir: OUTPUT_DIR,
  // Wagons (siblings of core, not descendants) have no node_modules of
  // their own and can't reach core's via esbuild's normal upward search -
  // nodePaths adds it as an extra lookup root.
  nodePaths: [path.resolve("node_modules")],
  plugins: [coffeePlugin, controllersAliasPlugin],
  loader: { ".woff": "file", ".woff2": "file", ".ttf": "file", ".eot": "file", ".svg": "file" },
  sourcemap: true,
  minify: process.env.NODE_ENV === "production",
  logLevel: "info",
};

// `yarn build --watch` only rebuilds files already in the bundle - a new
// controller/pack file, or switching wagons, needs a fresh `yarn build`
// run since the generated import lists above are written once, upfront.
if (process.argv.includes("--watch")) {
  esbuild
    .context(buildOptions)
    .then((ctx) => ctx.watch())
    .catch(() => process.exit(1));
} else {
  esbuild.build(buildOptions).catch(() => process.exit(1));
}
