// Copyright (c) 2026, hitobito AG. This file is part of
// hitobito and licensed under the Affero General Public License version 3
// or later. See the COPYING file at the top-level directory or at
// https://github.com/hitobito/hitobito.

// Replaces webpack + config/webpack/environment.js. Before bundling, this
// script (re)writes a handful of generated files that stand in for what
// webpack's `require.context()` used to do dynamically at runtime - esbuild
// has no equivalent, so the explicit import lists are generated here instead,
// from tmp/wagon_assets_manifest.json (written by `rake
// assets:wagon_js_manifest`, which is scoped to *active* wagons only, i.e.
// Wagons.all - not every hitobito_* directory that happens to be checked out).

const { execFileSync } = require("child_process");
const esbuild = require("esbuild");
const { sync: globSync } = require("glob");
const coffeescript = require("coffeescript");
const fs = require("fs");
const path = require("path");

const WAGON_MANIFEST_PATH = "tmp/wagon_assets_manifest.json";
const GENERATED_JS_DIR = "app/javascript/generated";
const OUTPUT_DIR = "app/assets/builds";

// `rake assets:render_js_entries assets:wagon_js_manifest` (which renders
// gem-provided ERB entries and lists the *active* wagons' JS-relevant
// files) are wired as Rake prerequisites of `javascript:build`, but this
// script also runs directly via `yarn build` (e.g. the Procfile's `js`
// process in normal dev mode) - a plain `yarn`/`node` invocation never goes
// through Rake at all, so those steps need to run here too, or switching
// WAGONS would silently keep bundling whichever wagon was last rendered.
execFileSync("bundle", ["exec", "rake", "assets:render_js_entries", "assets:wagon_js_manifest"], { stdio: "inherit" });

fs.mkdirSync(GENERATED_JS_DIR, { recursive: true });

// Lets `import { Controller } from "controllers"` (used by
// app/components/*_controller.js) resolve to app/javascript/controllers,
// mirroring webpacker's `resolve.modules` include of app/javascript.
const controllersAliasPlugin = {
  name: "controllers-alias",
  setup(build) {
    build.onResolve({ filter: /^controllers$/ }, () => ({
      path: path.resolve("app/javascript/controllers/index.js"),
    }));
  },
};

const wagons = fs.existsSync(WAGON_MANIFEST_PATH)
  ? JSON.parse(fs.readFileSync(WAGON_MANIFEST_PATH, "utf8"))
  : [];

const GENERATED_HEADER = "// Generated by esbuild.config.js - do not edit, regenerated on every build.\n";

const coffeePlugin = {
  name: "coffeescript",
  setup(build) {
    build.onLoad({ filter: /\.coffee$/ }, (args) => {
      const contents = coffeescript.compile(fs.readFileSync(args.path, "utf8"), { bare: true });
      return { contents, loader: "js" };
    });
  },
};

// --- app/javascript/generated/wagon_scripts.js ---
// Replaces the old app/javascript/javascripts/wagons.js.erb (its image
// require.context is dropped entirely - Propshaft serves wagon images
// directly, see config/initializers/assets.rb).
const wagonScriptImports = wagons
  .filter((wagon) => wagon.wagonScript)
  .map((wagon) => `import ${JSON.stringify(wagon.wagonScript)};`)
  .join("\n");
fs.writeFileSync(
  path.join(GENERATED_JS_DIR, "wagon_scripts.js"),
  `${GENERATED_HEADER}${wagonScriptImports}\n`
);

// --- app/javascript/generated/core_modules.js ---
// Replaces core.js's requireAll(require.context('../javascripts/modules', ...)).
const coreModuleImports = globSync("app/javascript/javascripts/modules/**/*.{js,coffee}")
  .map((file) => `import ${JSON.stringify(path.resolve(file))};`)
  .join("\n");
fs.writeFileSync(
  path.join(GENERATED_JS_DIR, "core_modules.js"),
  `${GENERATED_HEADER}${coreModuleImports}\n`
);

// --- app/javascript/controllers/generated_index.js ---
// Replaces the four require.context() calls that used to live in
// controllers/index.js (core controllers, component controllers, and
// wagon controllers in both the sibling-dev and vendor/wagons layouts -
// Wagons.all/wagon.paths.path already resolves correctly in either case,
// so there's no need to distinguish the two here).
// Stimulus's own naming convention (see stimulus/webpack-helpers'
// definitionsFromContext, which used to do this for us via
// require.context): a controller's identifier is its path *relative to its
// controllers root*, with the _controller.js suffix stripped, each path
// segment's underscores turned to dashes, and segments joined with "--" -
// so app/javascript/controllers/events/question_template_nested_form_controller.js
// becomes "events--question-template-nested-form", not just
// "question-template-nested-form" (which silently drops the "events--"
// namespace and breaks any data-controller="events--..." in the DOM).
function controllerIdentifier(controllersRoot, filePath, wagonName) {
  const relative = path.relative(controllersRoot, filePath).replace(/_controller\.js$/, "");
  const base = relative.split(path.sep).map((segment) => segment.replace(/_/g, "-")).join("--");
  if (!wagonName) return base;
  return `${wagonName.replace(/^hitobito_/, "").replace(/_/g, "-")}--${base}`;
}

const controllerEntries = [
  ...globSync("app/javascript/controllers/**/*_controller.js").map((file) => ({
    file: path.resolve(file),
    identifier: controllerIdentifier(path.resolve("app/javascript/controllers"), path.resolve(file)),
  })),
  ...globSync("app/components/**/*_controller.js").map((file) => ({
    file: path.resolve(file),
    identifier: controllerIdentifier(path.resolve("app/components"), path.resolve(file)),
  })),
  ...wagons.flatMap((wagon) =>
    wagon.controllers.map((file) => ({
      file,
      identifier: controllerIdentifier(wagon.controllersRoot, file, wagon.name),
    }))
  ),
];

const controllerLines = controllerEntries.map(
  (entry, i) => [`import Controller${i} from ${JSON.stringify(entry.file)};`, entry.identifier, i]
);
fs.writeFileSync(
  path.join("app/javascript/controllers", "generated_index.js"),
  `${GENERATED_HEADER}${controllerLines.map(([importLine]) => importLine).join("\n")}

export function registerGeneratedControllers(application) {
${controllerLines.map(([, identifier, i]) => `  application.register(${JSON.stringify(identifier)}, Controller${i});`).join("\n")}
}
`
);

// --- Bundle ---
const coreEntries = ["application", "core", "pass_verify"].map((name) => `app/javascript/packs/${name}.js`);
const wagonEntries = wagons.flatMap((wagon) => wagon.packs);

// Prune stale JS outputs left over from a *different* wagon (e.g. a
// previous wagon's agenda.js, when the newly active one has no such pack)
// - only touches *.js/*.js.map, so this can't clobber the CSS build's own
// outputs (which are plain *.css, --no-source-map).
const expectedBasenames = new Set(
  [...coreEntries, ...wagonEntries].flatMap((entry) => {
    const base = path.basename(entry, ".js");
    return [`${base}.js`, `${base}.js.map`];
  })
);
for (const existing of [...globSync(`${OUTPUT_DIR}/*.js`), ...globSync(`${OUTPUT_DIR}/*.js.map`)]) {
  if (!expectedBasenames.has(path.basename(existing))) fs.unlinkSync(existing);
}

const buildOptions = {
  entryPoints: [...coreEntries, ...wagonEntries],
  bundle: true,
  outdir: OUTPUT_DIR,
  // Wagons have no node_modules of their own (see hitobito_*/app/javascript
  // - they rely entirely on core's) and, being siblings of core rather than
  // nested under it, esbuild's normal upward node_modules search from a
  // wagon file never reaches core's node_modules at all. `nodePaths` adds
  // it as an extra lookup root, mirroring the old webpack config's
  // `environment.resolvedModules.append("core_node_modules", ...)`.
  nodePaths: [path.resolve("node_modules")],
  plugins: [coffeePlugin, controllersAliasPlugin],
  loader: { ".woff": "file", ".woff2": "file", ".ttf": "file", ".eot": "file", ".svg": "file" },
  sourcemap: true,
  minify: process.env.NODE_ENV === "production",
  logLevel: "info",
};

// `yarn build --watch` (Procfile) rebuilds on changes to files already in
// the bundle. A *new* controller/pack/wagon.js.coffee file - or switching
// which wagons are active - needs a fresh `yarn build` run to be picked up,
// since the generated import lists above are only (re)written once, here,
// before the build starts.
if (process.argv.includes("--watch")) {
  esbuild
    .context(buildOptions)
    .then((ctx) => ctx.watch())
    .catch(() => process.exit(1));
} else {
  esbuild.build(buildOptions).catch(() => process.exit(1));
}
