---
openapi: 3.0.1
info:
  title: JSON:API
  version: v1
paths:
  "/api/people":
    get:
      summary: list people
      parameters:
      - name: include
        in: query
        required: false
        explode: false
        schema:
          type: array
          enum:
          - phone_numbers
          - social_accounts
          - additional_emails
          nullable: true
          description: Contactables
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
