---
openapi: 3.0.1
info:
  title: JSON:API
  version: v1
paths:
  "/api/people":
    get:
      summary: list people
      parameters:
      - name: include
        in: query
        required: false
        explode: false
        schema:
          type: array
          enum:
          - phone_numbers
          - social_accounts
          - additional_emails
          - roles
          nullable: true
      responses:
        '200':
          description: successful
components:
  securitySchemes:
    ServiceTokenAuthHeader:
      type: apiKey
      in: header
      name: X-TOKEN
    ServiceTokenAuthParam:
      type: apiKey
      in: query
      name: token
    SessionAuth:
      type: apiKey
      in: cookie
      name: _session_id
security:
- ServiceTokenAuth: []
  SessionAuthHeader: []
  SessionAuthParam: []
