---
openapi: 3.0.1
info:
  title: JSON:API
  version: v1
paths:
  "/api/groups":
    get:
      summary: list groups
      parameters:
      - name: include
        in: query
        required: false
        explode: false
        schema:
          type: array
          enum:
          - contact
          - creator
          - updater
          - deleter
          - parent
          - layer_group
          nullable: true
      - name: extra_fields
        in: query
        required: false
        schema:
          type: string
          enum:
          - logo
      - name: filter[type][eq]
        in: query
        required: false
        schema:
          type: string
          enum:
          - Group::TopLayer
          - Group::TopGroup
          - Group::BottomLayer
          - Group::BottomGroup
          - Group::MountedAttrsGroup
          - Group::GlobalGroup
      responses:
        '200':
          description: successful
  "/api/groups/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: fetch group
      responses:
        '200':
          description: successful
  "/api/people":
    get:
      summary: list people
      parameters:
      - name: include
        in: query
        required: false
        explode: false
        schema:
          type: array
          enum:
          - phone_numbers
          - social_accounts
          - additional_emails
          - primary_group
          - layer_group
          - roles
          - roles.layer_group
          - roles.group
          - roles.group.parent
          - roles.group.layer_group
          nullable: true
      - name: filter[updated_at][gte]
        in: query
        required: false
        schema:
          type: string
          format: date
      responses:
        '200':
          description: successful
  "/api/people/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: fetch person
      parameters:
      - name: include
        in: query
        required: false
        explode: false
        schema:
          type: array
          enum:
          - phone_numbers
          - social_accounts
          - additional_emails
          - primary_group
          - layer_group
          - roles
          - roles.layer_group
          - roles.group
          - roles.group.parent
          - roles.group.layer_group
          nullable: true
      responses:
        '200':
          description: successful
    patch:
      summary: update person
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID
                    type:
                      type: string
                      enum:
                      - people
                      default: people
                    attributes:
                      type: object
                      properties:
                        first_name:
                          type: string
                        last_name:
                          type: string
                      description: Person attributes
                    extra_fields:
                      type: array
                      items:
                        type: string
                included:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum:
                        - contact
                        - creator
                        - updater
                        - deleter
                        - parent
                        - layer_group
                        default: contact
                      id:
                        type: string
                      attributes:
                        type: object
                        properties:
                          number:
                            type: string
components:
  securitySchemes:
    ServiceTokenAuthHeader:
      type: apiKey
      in: header
      name: X-TOKEN
    ServiceTokenAuthParam:
      type: apiKey
      in: query
      name: token
    SessionAuth:
      type: apiKey
      in: cookie
      name: _session_id
security:
- ServiceTokenAuthHeader: []
  ServiceTokenAuthParam: []
consumes:
- application/vnd.api+json
produces:
- application/vnd.api+json
