#!/bin/bash

set -ex

# this script is executed after our rails images default assemble script.

pushd /opt/app-root/src

# load development seeds when demo instance
if [[ $DEMO_INSTANCE -eq 1 ]]; then
  echo 'demo instance: creating symlink for loading development seeds'
  for wagon in vendor/wagons/*
  do
    cd $wagon/db/seeds
    ln -s development production
  done
fi

if [[ $PULL_TRANSIFEX -eq 1 ]]; then
  echo 'pulling transifex translations ...'
  RAILS_HOST_NAME='build.hitobito.ch' bundle exec rake tx:pull tx:wagon:pull -t
fi

BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "(built at: $BUILD_DATE)" > BUILD_INFO

popd
