#!/bin/bash

set -ex

# This script is executed after our rails images' default assemble script.

pushd /opt/app-root/src

bundle exec rake db:seed
bundle exec rake wagon:migrate
bundle exec rake wagon:seed

for dir in vendor/wagons/*; do
  if [[ -x $dir/.s2i/post_deploy ]] ; then
    $dir/.s2i/post_deploy
  fi
done

popd
