#!/bin/bash

set -ex

source_dir=$(dirname $0)/..

# this script places the core and wagon files in the right folders and creates the Wagonfile.
# after this, we are able to use our rails images default assemble script to do the execute default
# tasks like assets precompilation

pushd $source_dir

# move core
mv hitobito/* .

# add wagon sources
mkdir vendor/wagons
for dir in hitobito_*; do
  if [[ ( -d $dir ) ]]; then
    mv $dir vendor/wagons/
  fi
done

# place Wagonfile
mv -f config/rpm/Wagonfile .

# move hidden core dirs
rm -f .s2i/pre_assemble
cp -rf hitobito/.s2i . # cannot be moved since it is in use during this script's execution
mv hitobito/.tx .

# finally remove core source directory
rm -rf hitobito

# TODO: Investigate. This seems ugly and is a hack to prevent assemble from failing with
#
#     You are trying to install in deployment mode after changing
#     your Gemfile. Run `bundle install` elsewhere and add the
#     updated Gemfile.lock to version control.

#     You have added to the Gemfile:
#     * source: source at /home/sraez/dev/hitobito_generic_composition_apply/vendor/wagons/hitobito_generic
#     * hitobito_generic

#     You have deleted from the Gemfile:
#     * source: source at ../hitobito_insieme
#     * hitobito_insieme
# This inludes fixes from https://github.com/bundler/bundler/issues/2854#issuecomment-38991901
bundle install --no-deployment --path vendor/bundle
# Speed up the second `bundle install` run
bundle package --all

popd
