// Copyright (c) 2026, hitobito AG. This file is part of
// hitobito and licensed under the Affero General Public License version 3
// or later. See the COPYING file at the top-level directory or at
// https://github.com/hitobito/hitobito.

// Bundles the entrypoints - every .js in app/javascript/entrypoints, plus the
// ones the active wagons bring along (tmp/wagon_js_manifest.json, written
// by `rake assets:wagon_js_manifest`).

import esbuild from "esbuild";
import { globSync } from "glob";
import coffeescript from "coffeescript";
import fs from "fs";
import path from "path";

const WAGON_MANIFEST_PATH = "tmp/wagon_js_manifest.json";
const GENERATED_JS_DIR = "app/javascript/generated";
const GENERATED_HEADER = "// Generated by config/esbuild.mjs - do not edit, regenerated on every build.\n";

const { buildDir, wagons } = JSON.parse(fs.readFileSync(WAGON_MANIFEST_PATH, "utf8"));

// Output goes to a subdirectory per instance, i.e. per wagon composition (see
// config/initializers/assets.rb), so switching wagons, or running specs from a
// wagon's own directory, doesn't clobber a valid build.
const OUTPUT_DIR = path.join("app/assets/builds", buildDir);

const coffeePlugin = {
  name: "coffeescript",
  setup(build) {
    build.onLoad({ filter: /\.coffee$/ }, (args) => {
      const contents = coffeescript.compile(fs.readFileSync(args.path, "utf8"), { bare: true });
      return { contents, loader: "js" };
    });
  },
};

// Stimulus identifier convention: path relative to the controllers root,
// `_controller.js` stripped, underscores->dashes per segment, joined with "--"
// - e.g. events/question_template_nested_form_controller.js becomes
// "events--question-template-nested-form" (dropping the "events--" prefix would
// break any data-controller="events--..." in the DOM).
function controllerIdentifier(controllersRoot, filePath, wagonName) {
  const relative = path.relative(controllersRoot, filePath).replace(/_controller\.js$/, "");
  const base = relative.split(path.sep).map((segment) => segment.replace(/_/g, "-")).join("--");
  if (!wagonName) return base;
  return `${wagonName.replace(/^hitobito_/, "").replace(/_/g, "-")}--${base}`;
}

function writeGenerated(name, contents) {
  fs.writeFileSync(path.join(GENERATED_JS_DIR, name), `${GENERATED_HEADER}${contents}\n`);
}

// esbuild resolves imports statically, so everything that used to be collected
// at runtime is written out as explicit import lists first, on every build.
//
// `--watch` rebuilds when a file already in the bundle changes, so an edited
// controller is picked up, but a newly added one is not: it is in no bundle
// yet, and so in nothing esbuild watches. Adding, removing or renaming a
// controller, an entrypoint or a module needs a restart of the watcher - as
// does switching WAGONS, which additionally needs the manifest rewritten.
const generateImportListsPlugin = {
  name: "generate-import-lists",
  setup(build) {
    build.onStart(() => {
      fs.mkdirSync(GENERATED_JS_DIR, { recursive: true });

      writeGenerated(
        "wagon_scripts.js",
        wagons
          .filter((wagon) => wagon.wagonScript)
          .map((wagon) => `import ${JSON.stringify(wagon.wagonScript)};`)
          .join("\n")
      );

      writeGenerated(
        "core_modules.js",
        globSync("app/javascript/modules/**/*.{js,coffee}")
          .map((file) => `import ${JSON.stringify(path.resolve(file))};`)
          .join("\n")
      );

      // Core, component and wagon controllers. Wagons.all/wagon.paths.path
      // resolves correctly in both the sibling-dev and the vendor/wagons
      // layout, so there is no need to distinguish them here.
      const controllers = [
        ...globSync("app/javascript/controllers/**/*_controller.js").map((file) => ({
          file: path.resolve(file),
          identifier: controllerIdentifier(path.resolve("app/javascript/controllers"), path.resolve(file)),
        })),
        ...globSync("app/components/**/*_controller.js").map((file) => ({
          file: path.resolve(file),
          identifier: controllerIdentifier(path.resolve("app/components"), path.resolve(file)),
        })),
        ...wagons.flatMap((wagon) =>
          wagon.controllers.map((file) => ({
            file,
            identifier: controllerIdentifier(wagon.controllersRoot, file, wagon.name),
          }))
        ),
      ];

      writeGenerated(
        "controllers.js",
        `${controllers.map(({ file }, i) => `import Controller${i} from ${JSON.stringify(file)};`).join("\n")}

export function registerGeneratedControllers(application) {
${controllers.map(({ identifier }, i) => `  application.register(${JSON.stringify(identifier)}, Controller${i});`).join("\n")}
}`
      );
    });
  },
};

const buildOptions = {
  entryPoints: [
    ...globSync("app/javascript/entrypoints/*.js"),
    ...wagons.flatMap((wagon) => wagon.entrypoints),
  ],
  bundle: true,
  outdir: OUTPUT_DIR,
  // Wagons (siblings of core, not descendants) have no node_modules of their
  // own and can't reach core's via esbuild's normal upward search - nodePaths
  // adds it as an extra lookup root.
  nodePaths: [path.resolve("node_modules")],
  plugins: [coffeePlugin, generateImportListsPlugin],
  loader: { ".woff": "file", ".woff2": "file", ".ttf": "file", ".eot": "file", ".svg": "file" },
  sourcemap: true,
  minify: process.env.NODE_ENV === "production",
  logLevel: "info",
};

if (process.argv.includes("--watch")) {
  esbuild
    .context(buildOptions)
    .then((ctx) => ctx.watch())
    .catch(() => process.exit(1));
} else {
  esbuild.build(buildOptions).catch(() => process.exit(1));
}
