#!/bin/bash

if [ -z "$RAILS_ENV" ]
then
  env="development"
else
  env=$RAILS_ENV
fi

export RAILS_DB_ADAPTER=mysql2
export RAILS_DB_NAME=hitobito_$env
#export RAILS_DB_NAME=hitobito_production
export RAILS_DB_USERNAME=root
export RAILS_DB_PASSWORD=root
#export RAILS_DB_SOCKET=/var/lib/mysql/mysql.sock
export RAILS_DB_SOCKET=/var/run/mysqld/mysqld.sock

$@
