name: "Notify statuscope of the Job-Result"

on:
  workflow_call:
    inputs:
      application:
        description: "Name of the application in statuscope"
        type: string
        required: true
      result:
        description: "Result to report to statuscope"
        type: boolean
        required: true
    secrets:
      HEARTBEAT_URL:
        required: true
      HEARTBEAT_TOKEN:
        required: true

jobs:
  notify-statuscope:
    runs-on: 'ubuntu-latest'
    env:
      HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
      HEARTBEAT_TOKEN: ${{ secrets.HEARTBEAT_TOKEN }}
      HEARTBEAT_APPLICATION: ${{ inputs.application }}

    steps:
      - name: 'Check Configuration'
        run: |
          echo "HEARTBEAT_APPLICATION is ${{ env.HEARTBEAT_APPLICATION }}"

          (
          [[ "${{ env.HEARTBEAT_URL }}" != '' ]] &&
          [[ "${{ env.HEARTBEAT_TOKEN }}" != '' ]] &&
          echo "HEARTBEAT_URL and HEARTBEAT_TOKEN are present."
          ) || (
          echo "Please ensure that you have HEARTBEAT_URL and HEARTBEAT_TOKEN set as secrets"
          exit 1
          )

      - name: 'Send success'
        if: ${{ inputs.result == true }}
        run: >
          curl --silent ${{ env.HEARTBEAT_URL }}/signal \
            -d application=${{ env.HEARTBEAT_APPLICATION }} \
            -d token=${{ env.HEARTBEAT_TOKEN }} \
            -d status=ok | jq .

      - name: 'Send failure'
        if: ${{ inputs.result == false }}
        run: >
          curl --silent ${{ env.HEARTBEAT_URL }}/signal \
            -d application=${{ env.HEARTBEAT_APPLICATION }} \
            -d token=${{ env.HEARTBEAT_TOKEN }} \
            -d status=fail | jq .

