name: "Notify statuscope of the Job-Result"

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository that the action is being run in"
        type: string
        required: true
      test_result:
        description: "Result of the Test-Run to report to statuscope"
        type: boolean
        required: true
    secrets:
      HEARTBEAT_URL:
        required: false
      HEARTBEAT_TOKEN:
        required: false

jobs:
  notify-statuscope:
    runs-on: 'ubuntu-latest'
    env:
      HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
      HEARTBEAT_TOKEN: ${{ secrets.HEARTBEAT_TOKEN }}
      HEARTBEAT_APPLICATION: "${{ inputs.repository }}-tests"

    steps:
      - name: 'Check Configuration'
        id: check_config
        run: |
          echo "HEARTBEAT_APPLICATION is ${{ env.HEARTBEAT_APPLICATION }}"

          if [[ "${{ env.HEARTBEAT_URL }}" != '' ]] && [[ "${{ env.HEARTBEAT_TOKEN }}" != '' ]]; then
            echo "HEARTBEAT_URL and HEARTBEAT_TOKEN are present."
            echo "secrets_present=true" >> $GITHUB_OUTPUT
          else
            echo "HEARTBEAT_URL or HEARTBEAT_TOKEN not set — skipping statuscope notification."
            echo "secrets_present=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Send success'
        if: ${{ inputs.test_result == true && steps.check_config.outputs.secrets_present == 'true' }}
        run: >
          curl --silent ${{ env.HEARTBEAT_URL }}/signal \
            -d application=${{ env.HEARTBEAT_APPLICATION }} \
            -d token=${{ env.HEARTBEAT_TOKEN }} \
            -d status=ok | jq .

      - name: 'Send failure'
        if: ${{ inputs.test_result == false && steps.check_config.outputs.secrets_present == 'true' }}
        run: >
          curl --silent ${{ env.HEARTBEAT_URL }}/signal \
            -d application=${{ env.HEARTBEAT_APPLICATION }} \
            -d token=${{ env.HEARTBEAT_TOKEN }} \
            -d status=fail | jq .

