name: 'Wagon tests'

on:
  workflow_dispatch:
    inputs:
      core_ref:
        description: Use a specific version of the core for the workflow run. Defaults to the main branch (master, or sac-master during a merge freeze).
        default: ""
      wagon_dependency_ref:
        description: Use a specific version of the wagon dependency for the workflow run. Defaults to the main branch (master, or sac-master during a merge freeze).
        default: ""
      wagon_ref:
        description: Use a specific version of the wagon dependency for the workflow run. Defaults to the main branch (master).
        default: ""
  push:
    branches: [ master, sac-master ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'VERSION'
  #pull_request: # this trigger is disabled for now, because it caused our CI runners to be occupied too often
  #  paths-ignore:
  #    - 'doc/**'
  #    - '**.md'
  #    - 'VERSION'
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # auto-cancel previous runs of this same workflow on the same PR, if any are still running
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }} # never cancel runs triggered by the main branch, to allow finding the exact merge that broke a wagon

jobs:
  find-wagons:
    name: 'Find all Puzzle-managed wagons'
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'run-wagon-tests!') }}
    runs-on: 'ubuntu-latest'
    outputs:
      wagons: ${{ steps.list-wagon-repositories.outputs.wagons }}

    steps:
      - name: 'List wagon repositories'
        id: list-wagon-repositories
        run: |
          WAGONS=$(gh repo list hitobito -L 100 --no-archived --json owner,name | \
            jq -c --arg skip "$SKIP_WAGONS" '($skip | split(" ")) as $skipped |
              map(select(.name | startswith("hitobito_")) |
                { owner: .owner.login, repo: .name, name: .name | ltrimstr("hitobito_") } |
                select(.name | IN($skipped[]) | not))')
          echo "$WAGONS"
          echo "wagons=$WAGONS" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_WAGONS: ${{ vars.WAGON_TESTS_SKIP_WAGONS }}

  run-wagon-tests:
    name: 'Run ${{ matrix.wagon.name }} wagon tests'
    needs:
      - find-wagons
    strategy:
      fail-fast: false
      matrix:
        wagon: ${{ fromJSON(needs.find-wagons.outputs.wagons) }}
      max-parallel: 5 # needed so the wagon matrix does not occupy all the runners at once

    uses: ./.github/workflows/wagon-tests.yml
    with:
      wagon_repository: ${{ matrix.wagon.repo }}
      core_ref: ${{ inputs.core_ref || github.ref }}
      wagon_ref: ${{ inputs.wagon_ref || '' }}
      wagon_dependency_ref: ${{ inputs.wagon_dependency_ref || '' }}
    secrets:
      HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
      HEARTBEAT_TOKEN: ${{ secrets.HEARTBEAT_TOKEN }}
