name: 'Rails Lint and Test'

on:

jobs:
  rubocop:
    runs-on: 'ubuntu-22.04'
    env:
      RAILS_DB_ADAPTER: nulldb

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Prepare'
        uses: ./.github/actions/core-ci-setup
        with:
          database: false
          assets: false

      - name: 'Rubocop'
        run: |
          bundle exec rake rubocop
