name: 'Core - Consolidate patches'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: write

jobs:
  patches:
    runs-on: 'ubuntu-latest'
    env:
      RAILS_DB_ADAPTER: nulldb

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.RELEASE_PREPARATION_TOKEN }}

      - name: 'Prepare'
        uses: ./.github/actions/core-ci-setup
        with:
          database: false
          assets: false

      - name: Download and consolidate patches
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PREPARATION_TOKEN }}
        run: |
          gh --version
          bundle exec rake wagon:patches:consolidate
          git status

      - name: Commit patches
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: ".patches.yml .patches/*"
          commit_message: "[skip-ci] Consolidating patches"
          push_options: '--force'
