name: "Wagon - Update Patches"

on:
  workflow_call:
    inputs:
      wagon_repository:
        description: "Wagon repository, e.g. hitobito_pbs"
        type: string
      wagon_dependency_repository:
        description: A wagon this wagon depends on, e.g. hitobito_youth
        required: false
        default: ""
        type: string
      core_ref:
        description: Use a specific version of the core for the workflow run. Defaults to master.
        type: string
        default: ""
      wagon_dependency_ref:
        description: Use a specific version of the wagon dependency for the workflow run. Defaults to master.
        type: string
        default: ""
      main_branch:
        description: Speficy which branch should be regarded as the main branch of core and dependency wagon. Statuscope will only be notified if the core and dependency refs match this branch.
        type: string
        default: master

defaults:
  run:
    working-directory: hitobito

jobs:
  wagon_patches:
    runs-on: "ubuntu-22.04"
    env:
      HEADLESS: true
      RAILS_DB_ADAPTER: postgresql
      RAILS_DB_HOST: 127.0.0.1
      RAILS_DB_PORT: 5432
      RAILS_DB_USERNAME: hitobito
      RAILS_DB_PASSWORD: hitobito
      RAILS_DB_NAME: hitobito_test
      RAILS_TEST_DB_NAME: hitobito_test
      RAILS_ENV: test
      DISABLE_TEST_SCHEMA_MAINTENANCE: true
    permissions:
      contents: write

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: hitobito
          POSTGRES_PASSWORD: hitobito
          POSTGRES_DB: hitobito_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U hitobito"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: "memcached"
        ports: ["11211:11211"]

    steps:
      - name: Check out the core, which contains the shared setup action
        uses: actions/checkout@v4
        with:
          repository: hitobito/hitobito
          ref: ${{ inputs.core_ref }}
          path: .hitobito_core_repo
          fetch-depth: 1

      - name: "Prepare"
        uses: ./.hitobito_core_repo/.github/actions/wagon-ci-setup
        with:
          assets: false
          wagon_repository: ${{ inputs.wagon_repository }}
          wagon_dependency_repository: ${{ inputs.wagon_dependency_repository }}
          core_ref: ${{ inputs.core_ref }}
          wagon_dependency_ref: ${{ inputs.wagon_dependency_ref }}

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run ${{ inputs.wagon_repository }} patch generation
        working-directory: ${{ inputs.wagon_repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec rake app:wagon:patches:generate
          git add .patches.yml
          git status
          git config user.name "Github Action Patches updater"
          git config user.email "robot@puzzle.ch"
          git commit -m "Updating patches" || true
          git push
